### ISSUE TITLE
Mentors, Assignees for 2018

### ISSUE THREAD

**Issue by biswesh456** [adityathiru/IIITB-StudentKit#26]
Mentor - Tanishq @tanishq1g 
Assignee - Mudita @muditabaid 
Assignee - Aravind @r-arvind

**Comment by vibhavagarwal5** [comment]
New Assignees: <br>
Mentor - Tanishq @tanishq1g 
Assignee - Mudita @muditabaid
Assignee - Ananya @AnanyaAppan 
Assignee - Anubhav @timetraveller05
