### ISSUE TITLE
Add Home Button

### ISSUE THREAD

**Issue by GaganAgarwal77** [adityathiru/IIITB-StudentKit#79]
Add a home button to the overlay to allow going back to the landing page from every page.

**Comment by Dhamodhar-DDR** [comment]
There is already a close button in every page (except the key officials page) which serves the same purpose right !?

**Comment by GaganAgarwal77** [comment]
Yes, but when you open a page directly from a new window, say [this](https://studentkit.zense.co.in/#clubs), on hitting the close button you will be sent back to the empty window instead of the home page.
