### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by divyamagwl** [adityathiru/IIITB-StudentKit#81]
Write a short description about events like Umang, RMIT, IStem-Hackathon and add it to the events page.

**Comment by chhajed-ajay** [comment]
Umang is an inter-college sports event of the college. Sports included are Basketball, Football, Volleyball, Throw ball.

**Comment by divyamagwl** [comment]
> Umang is an inter-college sports event of the college. Sports included are Basketball, Football, Volleyball, Throw ball.

@chhajed-ajay Add some more details if possible like when it is organized, how long is the event etc. then send a PR. Also, it will be great if you find some photos which can be added with the description.
